import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { BookMinus, Home, SearchIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="border-4 md:border-green-500 border-yellow-500 lg:border-purple-500 xl:border-sky-500">
        <>{children}</>
      </body>
    </html>
  );
}
